attr_rate: 0.1
emo_rate: 0.3
emotion: all
learnable_property: ["object","scene"]
learning_rate: 0.0001
max_train_steps: 1000
model: MLP
need_Dropout: false
need_LN: false
need_ReLU: true
num_fc_layers: 3
num_train_epochs: 10
output_dir: runs/test
pretrained_model_name_or_path: /mnt/d/model/stable-diffusion-v1-5/
seed: 520
threshold: 0
train_data_dir: /mnt/d/dataset/EmoSet/0103_split_to_folder/
